service: bonuscappes
configValidationMode: off
provider:
  name: scaleway

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

custom:
  containers:
    first:
      directory: java-container
      description: Télécharge les bonus cappés de la Société Générale
      minScale: 1
      maxScale: 2
      memoryLimit: 128
      env:
        MODELE_INDICES: https://raw.githubusercontent.com/qlefevre/bonuscappes/main/xlsx/modele_indices.xlsx
